### ISSUE TITLE
[codelab] Failed to Compile message

### ISSUE THREAD

**Issue by krishnann2003** [material-components/material-components-web-codelabs#118] opened 2020-02-24 14:57 UTC
> mdc-101-web@0.0.0 start D:\NNK\SVASST\material-components-web-codelabs-master\mdc-101\starter
> webpack-dev-server --progress

 10% [3] building modules 1/1 modules 0 active
Project is running at http://localhost:8080/
webpack output is served from /
[2] Hash: 1b4f41ca2f549000defcfb05145d5149027b91e1b37c697c6ceb7175e813bf286aff6eb11afa0947
Version: webpack 3.12.0
Child
    Hash: 1b4f41ca2f549000defc
    Time: 3019ms
                    Asset    Size  Chunks                    Chunk Names
    style-bundle-login.js  331 kB       0  [emitted]  [big]  main
       [2] multi (webpack)-dev-server/client?http://localhost:8080 ./login.scss 40 bytes {0} [built]
       [3] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {0} [built]
       [4] ./node_modules/url/url.js 23.3 kB {0} [built]
       [5] ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 14.7 kB {0} [built]
       [7] ./node_modules/url/util.js 314 bytes {0} [built]
       [8] ./node_modules/querystring-es3/index.js 127 bytes {0} [built]
      [11] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
      [12] ./node_modules/ansi-regex/index.js 135 bytes {0} [built]
      [13] ./node_modules/loglevel/lib/loglevel.js 8.61 kB {0} [built]
      [14] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
      [15] ./node_modules/sockjs-client/dist/sockjs.js 181 kB {0} [built]
      [16] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
      [21] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
      [23] (webpack)/hot/emitter.js 77 bytes {0} [built]
      [25] ./login.scss 524 bytes {0} [built] [failed] [1 error]
        + 11 hidden modules

    ERROR in ./login.scss
    Module build failed:
    undefined
    ^
          @use is coming soon, but it's not supported in this version of Dart Sass.
       ╷
    23 │ @use "./mixins";
       │ ^^^^^^^^^^^^^^^
       ╵
      node_modules\@material\textfield\mdc-text-field.scss 23:1  root stylesheet
      stdin 2:9                                                  root stylesheet
          in D:\NNK\SVASST\material-components-web-codelabs-master\mdc-101\starter\node_modules\@material\textfield\mdc-text-field.scss (line 23, column 1)
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./login.scss
Child
    Hash: fb05145d5149027b91e1
    Time: 3014ms
                   Asset       Size  Chunks                    Chunk Names
         bundle-home.css  128 bytes          [emitted]
    style-bundle-home.js     331 kB       0  [emitted]  [big]  main
       [2] multi (webpack)-dev-server/client?http://localhost:8080 ./home.scss 40 bytes {0} [built]
       [3] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {0} [built]
       [4] ./node_modules/url/url.js 23.3 kB {0} [built]
       [5] ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 14.7 kB {0} [built]
       [7] ./node_modules/url/util.js 314 bytes {0} [built]
       [8] ./node_modules/querystring-es3/index.js 127 bytes {0} [built]
      [11] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
      [12] ./node_modules/ansi-regex/index.js 135 bytes {0} [built]
      [13] ./node_modules/loglevel/lib/loglevel.js 8.61 kB {0} [built]
      [14] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
      [15] ./node_modules/sockjs-client/dist/sockjs.js 181 kB {0} [built]
      [16] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
      [21] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
      [23] (webpack)/hot/emitter.js 77 bytes {0} [built]
      [25] ./home.scss 61 bytes {0} [built]
        + 11 hidden modules
Child
    Hash: b37c697c6ceb7175e813
    Time: 3299ms
              Asset    Size  Chunks                    Chunk Names
    bundle-login.js  516 kB       0  [emitted]  [big]  main
       [5] ./node_modules/@material/textfield/constants.js 2.71 kB {0} [built]
      [16] ./node_modules/@material/textfield/foundation.js 19.3 kB {0} [built]
      [22] multi (webpack)-dev-server/client?http://localhost:8080 ./login.js 40 bytes {0} [built]
      [23] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {0} [built]
      [24] ./node_modules/url/url.js 23.3 kB {0} [built]
      [25] ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 14.7 kB {0} [built]
      [27] ./node_modules/url/util.js 314 bytes {0} [built]
      [31] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
      [33] ./node_modules/loglevel/lib/loglevel.js 8.61 kB {0} [built]
      [34] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
      [36] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
      [41] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
      [43] (webpack)/hot/emitter.js 77 bytes {0} [built]
      [45] ./login.js 226 bytes {0} [built]
      [46] ./node_modules/@material/textfield/index.js 1.36 kB {0} [built]
        + 45 hidden modules
Child
    Hash: bf286aff6eb11afa0947
    Time: 3054ms
             Asset    Size  Chunks                    Chunk Names
    bundle-home.js  331 kB       0  [emitted]  [big]  main
       [2] multi (webpack)-dev-server/client?http://localhost:8080 ./home.js 40 bytes {0} [built]
       [3] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {0} [built]
       [4] ./node_modules/url/url.js 23.3 kB {0} [built]
       [5] ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 14.7 kB {0} [built]
       [7] ./node_modules/url/util.js 314 bytes {0} [built]
       [8] ./node_modules/querystring-es3/index.js 127 bytes {0} [built]
      [11] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
      [12] ./node_modules/ansi-regex/index.js 135 bytes {0} [built]
      [13] ./node_modules/loglevel/lib/loglevel.js 8.61 kB {0} [built]
      [14] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
      [15] ./node_modules/sockjs-client/dist/sockjs.js 181 kB {0} [built]
      [16] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
      [21] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
      [23] (webpack)/hot/emitter.js 77 bytes {0} [built]
      [25] ./home.js 13 bytes {0} [built]
        + 11 hidden modules
webpack: Failed to compile.

**Comment by suga0828** [comment] 2020-04-14 01:36
@krishnann2003 you could solve this issue updating the dart-sass dependency. Run de command:
`npm install --save-dev dart-sass` to update to version 1.25.0.

**Comment by abhiomkar** [comment] 2020-05-01 16:35
Closing this as duplicate of #121

As @suga0828 suggested please upgrade to latest version of dart-sass to use `@use` syntax.

**Closed by abhiomkar** 2020-05-01 16:35 UTC
