### ISSUE TITLE
[codelab] <Tried following your MDC101 tut, when doing npm install got this error>

### ISSUE THREAD

**Issue by hdsantos89** [material-components/material-components-web-codelabs#90] opened 2019-06-04 07:57 UTC
I haven't done anything different, I believe, to what https://codelabs.developers.google.com/codelabs/mdc-101-web/#1 instructs

```
➜  starter git:(master) npm install
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:152:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

**Comment by khamilton** [comment] 2019-06-20 20:34
I am also experiencing the same issue with the install.  6.20.19 @ 4:30pm.  I cloned the repository.

**Comment by abhiomkar** [comment] 2019-06-20 21:29
I'm not able to reproduce this with below npm / node versions:

```
$ npm --version
6.5.0

$ node --version
v11.9.0
```

**Comment by khamilton** [comment] 2019-06-21 01:00
Thanks so much for responding. I will check the version(s) and try again.

**Comment by abhiomkar** [comment] 2019-07-15 15:43
Given no further response, closing this issue.

**Closed by abhiomkar** 2019-07-15 15:43 UTC
