### ISSUE TITLE
[codelab] MDC-111 Web: Incorporating Material Components into your codebase (Web) Select Button not rendered properly

### ISSUE THREAD

**Issue by jpafable** [material-components/material-components-web-codelabs#115] opened 2020-02-12 08:31 UTC
![Select](https://user-images.githubusercontent.com/10781143/74316695-fa7a6a00-4db4-11ea-93b9-5cfa5dc949f6.png)
Select was not rendered properly after the tutorial.

Chrome logs the following error:
`bundle.js:15233 Uncaught Error: MDCSelect: Missing required element: The following selector must be present: '.mdc-select__selected-text'
    at MDCSelect.initialize (bundle.js:15233)
    at MDCSelect.MDCComponent (bundle.js:551)
    at new MDCSelect (bundle.js:15194)
    at Object.<anonymous> (bundle.js:14965)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:6063)
    at __webpack_require__ (bundle.js:20)
    at bundle.js:63
    at bundle.js:66`

**Comment by ryanolsonx** [comment] 2020-03-02 17:59
I got this too. :(

**Comment by abhiomkar** [comment] 2020-05-01 16:41
Please follow [documentation](https://material.io/develop/web/components/input-controls/select-menus/) on material.io site for latest guidance on select usage including updated HTML structure.

This happens if HTML structure mismatches with the MDC Web version that you're using.

Closing this as duplicate of #128

**Closed by abhiomkar** 2020-05-01 16:41 UTC
