### ISSUE TITLE
[codelab] <The guides have issues with version 6.0.0>

### ISSUE THREAD

**Issue by plug-n-play** [material-components/material-components-web-codelabs#132] opened 2020-04-23 20:00 UTC
While the guides work fine with version 4.0, it has issues with version 6

Steps to reproduce:
1. Goto `complete` folder
2. Run `yarn && yarn start` - everything works as expected
3. Remove `node_modules` - `rm -rf node_modules`
4. Remove all dependencies from package.json
5. Install the dependencies manually - `npm i @material/button @material/drawer @material/elevation @material/image-list @material/list @material/ripple @material/textfield @material/typography` - which currently install v 6.0
6. Do `yarn` to install dev dependencies
7. Try starting server `yarn start`
8. Observe we get this error:
```
ERROR in ./home.scss
    Module build failed: 
    @forward "@material/animation" as mdc-animation-*;
    ^
          Can't find stylesheet to import.
      ╷
    1 │ @forward "@material/animation" as mdc-animation-*;
      │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ╵
      node_modules/@material/ripple/_mixins.import.scss 1:1  @import
      stdin 5:9                                              root stylesheet
          in /Users/amandeep.bajwa/hdd/learn/material-design/material-components-web-codelabs/mdc-103/complete/node_modules/@material/ripple/_mixins.import.scss (line 1, column 1)
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./home.scss
Child
    Hash: ad64479063a4655d155e
    Time: 1364ms
```

**Comment by MewX** [comment] 2020-04-30 12:53
works with v5.1.0 as well

**Comment by abhiomkar** [comment] 2020-05-01 15:56
Marking this as Duplicate of #134

Please upgrade to latest Sass version to use latest Dart Sass syntax that supports `@use` rule. Follow [getting started](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md) guide for full setup instructions.

If you're following [MDC-101-web](https://codelabs.developers.google.com/codelabs/mdc-101-web/#3) codelab which suggests `@import` syntax, existing version of Sass should still work.

We'll update our codelabs to latest version of MDC Web (v6.0.0), please [follow this bug](https://github.com/material-components/material-components-web-codelabs/issues/135) for updates.

**Closed by abhiomkar** 2020-05-01 15:56 UTC
