### ISSUE TITLE
[codelab] mdc-101-web - Page fails to load after including "import" in login.scss file

### ISSUE THREAD

**Issue by ksurendra** [material-components/material-components-web-codelabs#120] opened 2020-03-03 22:21 UTC
Adding code as described on this page https://codelabs.developers.google.com/codelabs/mdc-101-web/#2 but the page fails to load properly as shown in the example.

**login.scss**
```
@import "./common";
@import "@material/textfield/mdc-text-field";

.header {
  text-align: center;
}

.shrine-logo {
  width: 150px;
  height: 150px;
  padding-top: 80px;
  fill: currentColor;
}

.username,
.password {
  display: block;
  width: 300px;
  margin: 20px auto;
}
```

**Error:**
`[WDS] Errors while compiling. Reload prevented.`

```
(undefined) ./login.scss
Module build failed: 
@use "./mixins";
^
      @use is coming soon, but it's not supported in this version of Dart Sass.
   ╷
23 │ @use "./mixins";
   │ ^^^^^^^^^^^^^^^
   ╵
  node_modules/@material/textfield/mdc-text-field.scss 23:1  root stylesheet
  stdin 2:9                                                  root stylesheet
      in /Users/suren/Personal/Projects/research/design/material/material-components-web-codelabs/mdc-101/starter/node_modules/@material/textfield/mdc-text-field.scss (line 23, column 1)
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./login.scss

```
**Screenshot:**
![Screen Shot 2020-03-03 at 4 18 39 PM](https://user-images.githubusercontent.com/902972/75825329-b7d00000-5d6a-11ea-86e4-cda5adbe2dfe.png)

**Comment by fractionofadot** [comment] 2020-03-08 17:25
Try:
`npm update dart-sass`

The `@use` statement was not supported in the version installed with the package.json. Updating solved the issue for me.

**Comment by rickertl** [comment] 2020-03-16 02:08
@fractionofadot Updating `dart-sass` fixed it for me as well. Thanks.

**Comment by AjithPG** [comment] 2020-03-30 11:38
my dart-sass verstion is  "dart-sass": "^1.25.0"
@use is coming soon, but it's not supported in this version of Dart Sass
How can i solve this

**Comment by abhiomkar** [comment] 2020-05-01 16:31
Closing this as duplicate of #121

**Closed by abhiomkar** 2020-05-01 16:31 UTC
