### ISSUE TITLE
build scss failed

### ISSUE THREAD

**Issue by eksea** [material-components/material-components-web-codelabs#50] opened 2018-07-21 05:47 UTC
I got this error when i run npm start. I still cannot resolve it after searching on goolge. 

ERROR in ./app.scss
    Module build failed: C:\Users\Jack\myworkspace\github\material-components-web-codelabs\mdc-101\starter\app.scss:1
    exports = module.exports = require("./node_modules/_css-loader@1.0.0@css-loader/lib/css-base.js")(false);
                                                                                                     ^

    TypeError: require(...) is not a function
        at C:\Users\Jack\myworkspace\github\material-components-web-codelabs\mdc-101\starter\app.scss:1:98
        at ContextifyScript.Script.runInContext (vm.js:59:29)
        at ContextifyScript.Script.runInNewContext (vm.js:65:15)
        at Object.extractLoader (C:\Users\Jack\myworkspace\github\material-components-web-codelabs\mdc-101\starter\node_modules\_extract-loader@2.0.1@extract-loader\lib\extractLoader.js:88:12)
     @ multi ./node_modules/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://localhost:8080 ./app.scss

**Comment by abhiomkar** [comment] 2018-07-24 15:53
Can please let us know what steps did you follow? What node & npm versions are you using?

**Comment by eksea** [comment] 2018-07-28 07:14
The node which i am using is v8.11.1, and the npm is 5.6.0
I followed the steps in the below tutorials. 
https://material.io/develop/web/docs/getting-started/
https://codelabs.developers.google.com/codelabs/mdc-101-web/

ps：
I resolved  the problem  by using extract-text-webpack-plugin at last.

**Comment by kfranqueiro** [comment] 2018-07-30 18:56
Hm. I tried reproducing this issue within the codelabs with the same versions of node and npm, on both Windows and OS X, but still was unable to see this error. The path `node_modules/_css-loader@1.0.0@css-loader/lib/...` also seems suspicious to me; the version of `css-loader` that ends up installed when following the `package-lock.json` in `mdc-101/starter` is 0.28.11 (and npm 5+ should honor `package-lock`).

Anyway, since you were able to resolve the issue, I'm going to close this. Thanks!

**Closed by kfranqueiro** 2018-07-30 18:56 UTC

**Comment by acdvorak** [comment] 2018-07-30 22:39
Glad to hear you solved the problem!

Closing this issue for now. If you think there's a bug in MDC, feel free to reopen 😀
