### ISSUE TITLE
[codelab] <Module build failed>

### ISSUE THREAD

**Issue by gokulayokesh** [material-components/material-components-web-codelabs#47] opened 2018-07-10 13:16 UTC
ERROR in ./app.scss
    Module build failed:
    undefined
                ^
          No mixin named mdc-rtl-reflexive
          in C:\Users\Gokulyokesh\Desktop\material-components-web-codelabs-maste
r\mdc-112\starter\node_modules\@material\textfield\_mixins.scss (line 505, colum
n 14)
     @ ./App.js 17:0-21
     @ ./index.js
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.js

**Comment by kfranqueiro** [comment] 2018-07-10 14:14
I wasn't able to reproduce this on the starter or complete code for MDC 112 out of the box, from a clean npm install.

What version of npm are you using? I ask because if it's older than 5.x, it's not honoring the `package-lock.json` in the folder, which might lead to version skew. (The latest npm version is 6.1.0 right now.)

**Comment by kfranqueiro** [comment] 2018-07-19 18:05
Given no further response, I'm going to close this issue. I would suggest ensuring your version of npm is up-to-date and try again.

**Closed by kfranqueiro** 2018-07-19 18:05 UTC
